name: Setup
description: Setup Bun and install packages (frozen lockfile)

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install packages
      shell: bash
      run: bun install --frozen-lockfile
